### ISSUE TITLE
Implement twitter scraper

### ISSUE THREAD

**Issue by NWChen** [NWChen/banshee#1]
Given an optional query, gather data and metadata from https://twitter.com - including (ideally) tweet author, date, list of retweets, list of comments, and/or location if possible.

@OriAboodi could you get this done by **Sunday (11/12)?**

**Comment by OriAboodi** [comment]
@NWChen- 2 questions:
- in order to use twitter API, we needed a registered account. I created an account and hardcoded the key and secret (which we definitely should not do). How do you think we should handle that? Environment variables? Should we also include this auth stuff in the app engine itself?
- Should we create a Banshee-specific twitter account? I put my email and number for now.

**Comment by OriAboodi** [comment]
@NWChen a few more comments :)
- we need to think of what calls we'd like to make to this scraper. I implemented: get all statuses of a screen-name. we can also perhaps create a streaming instance or do more. Other than the get statuses of a screen-name, anything else you think would be good?

**Comment by OriAboodi** [comment]
@NWChen last comment for tonight!
I finished up the scraper framework, wrote a test to make sure it does what we desire. Let's sync up when you finish your end to see what you will be expecting of this class and how we can make it most efficient!

**Comment by NWChen** [comment]
@OriAboodi perfect. Thanks!

Basic scraper interfaces I had in mind were:
- get tweets of a specific user
- get tweets containing a query (within a finite # of recent tweets)
- get tweets of users related to a single tweet, e.g. of users who retweeted/commented.

Ultimately up to you - will take a look ASAP

**Comment by OriAboodi** [comment]
@NWChen Cool, thanks!
So 1 is done, I'll try to set up 2 and 3
What did you mean by query? keywords filter?

**Comment by NWChen** [comment]
@OriAboodi 
> What did you mean by query? keywords filter?
yes, keywords

**Comment by OriAboodi** [comment]
@NWChen Finished 2 and 3. Will get on only http requests a little later in the week.
