### ISSUE TITLE
New Features implemented

### ISSUE THREAD

**Issue by OriAboodi** [NWChen/banshee#10]
Hey guys
side note: @NWChen I implemented a new interface for search requests. This should make it much easier for you to connect to. let me know if you have any questions
Some of what I included is: search by username, by "and" keywords, "or" keywords, exact phrase, location, and keywords + location. 👯‍♂️ 

@pr and @NWChen : There is no good way to get the location of a tweet by scraping it. However, I was able to find out how to search on tweets around a certain location within a certain mile radius. While this won't allow for visualization, it does allow for really great "real time" viewing of tweets that come in based on a certain location.

What do you guys think? take a look at the functionality I implemented. On both your ends, can you get it working by Tuesday?

**Comment by NWChen** [comment]
amazing, thank you @OriAboodi . n-mile radius sounds fine to me.

I'll be implementing realtime streaming and approximate location search on the backend by Tuesday.

**Comment by pr** [comment]
@OriAboodi I love the idea of n-mile radius. Great work! 

@NWChen happy to work on the visualization of the real time streaming once you implement it. Thanks!

**Comment by pr** [comment]
@OriAboodi Yes, I can work on that Monday night. The current state of the application is the format we will be using going forward? The "fire hose" will also return each tweet in json-type format?

**Comment by OriAboodi** [comment]
@pr : So there's two thing's we'll have to figure out:
1. portraying the tweets in a nicer format
2. portraying tweets as they come in, as you say "fire hose"

Yes, each tweet will be returned in the same way with the format I outlined above, and the format of the application seems good so far.

Let's make sure we get that it's a nice format when we come in on Tuesday we have it in a nice portrayal, and hopefully @NWChen will figure out "fire-hosing".

Additionally, I'll open up a new task for you to add query-types with the new back-end interface

**Comment by pr** [comment]
@OriAboodi Perfect, thanks! Makes perfect sense.
