### ISSUE TITLE
Query types in the front end

### ISSUE THREAD

**Issue by OriAboodi** [NWChen/banshee#11]
hey @pr 
We have a new back-end interface that allows for new requests.
The request types are:
- searching the latest tweets of a username
- searching the latest tweets for a: location and a mile radius (might be good to separate those)
- 2 for searching the latest tweets for keywords: one for OR type (if any of the ketwords come up, include that tweet), one for AND type (only if all of them do, include that tweet)
- searching for an exact phrase
- searching for both "AND" keywords and location + mile radius. 

Maybe you can work with @NWChen to see if he could handle combining some of them, like maybe for location with "AND" keywords?
Let's try to get at least the keyword and location working by tuesday

**Comment by pr** [comment]
Makes sense. Plan is to do this late Monday night. Thanks @OriAboodi

**Comment by pr** [comment]
@OriAboodi 
No more searching by date right? 
Can I search by just location without a mile radius? What is the default value for mile radius if none is given?
Can I search for an exact phrase in a location with a mile radius?

**Comment by pr** [comment]
Also is location given by name or zip code? What does the query accept?

**Comment by pr** [comment]
@OriAboodi Ok I pushed a first draft of the new index. Let me know how to make it better/more clear. I think I need to do a better job demarcating what is mandatory and what is not. The questions above will help I think. 

@NWChen What do you need me to do to help connect the front and the backend? I don't want to leave you in the lurch.

**Comment by pr** [comment]
Oh last questions sorry Ori, can you search for more than one exact phrase? If so how do you separate the phrases?

**Comment by NWChen** [comment]
@pr multiple-phrase queries are tokenized on the backend. If you'd like, I can return the following JSON structure to you:
```json
[
keyword1: {
   ...
},
keyword2: {
    ...
}
]
```

**Comment by OriAboodi** [comment]
@pr answers to your questions:
- A search for a location is by name, e.g. Chicago or something similar
- The default value I have for mile radius is 15 miles, so yes there can be a request with no mile radius
- I have not yet made the capability for more than 1 phrase. We can look into that next week if that's alright.
- No more searching by date, only the most recent tweets will come up
Let me know if there's anything else I can answer!

**Comment by pr** [comment]
@OriAboodi Perfect, that all makes sense to me. I'll try to make the index more clear to reflect that. Thanks for the info! 
Final question, can the user search for OR keywords and AND Keywords at the same time? So can I run a query where a tweet must contain the phrase "President of the United States", must include the word "Trump", and must include either "China" or "Japan". Is that too complicated?  

@NWChen That looks good to me. What would you like me to do with that JSON structure? Return it out with nice formatting? Where in this pipeline am I adding the formating? I haven't done anything like this before, but excited to learn,

**Comment by OriAboodi** [comment]
@pr with regards to your question to me- not yet! Right now it'll be separated. But we can do that on the next iteration. just need to figure out the logic that the twitter search does

**Comment by OriAboodi** [comment]
Also, @pr Just checked out the new draft, Nice job! 
- We need to figure out how to combine some of those queries to allow for a request like keywords + location.
- We also need to block/figure out what to do when the user puts two requests that can't be combined in. But this is good for this week's iteration!
