### ISSUE TITLE
Implement query forms

### ISSUE THREAD

**Issue by NWChen** [NWChen/banshee#4]
Allow the user to enter query data (e.g. Twitter username, date before/after a certain period, tweet keywords, # retweets etc.). Send that data via AJAX (or whatever else works to prevent the page from reloading on form submission) to the backend.

@pr can you get this done by **Sunday (11/12)?**

**Comment by pr** [comment]
@NWChen We don't need a map section just yet right, because we currently aren't using location data? 

Also I think you do need a password for the login, if only to prevent malicious users from altering your alerts. What do you think?

**Comment by NWChen** [comment]
@pr Agreed - let's keep the MVP simple (largely text on screen) for now.

I think for simplicity's sake we should stick to no passwords for now - we can think about a database for all user information once Twitter data starts showing up.

**Comment by pr** [comment]
@NWChen How does this look? What are the the results going to look like? I can also change this for if/when we add map functionality.

https://peter.net/banshee/

Also in the future where should I host the page? Do we have a Heroku yet?

**Comment by OriAboodi** [comment]
@pr Sweet, that looks like a nice first iteration! Results/tweets are probably going to come back as JSON format for now- we'll need to see later how we customize it/parse them to display in the most efficient way.

**Comment by NWChen** [comment]
@pr looks excellent. Will get back to you on how data gets interchanged after I implement the webserver.

We can stick to localhost development for most of our work, and push to a Heroku instance whenever we reach a presentable stage in our MVP development. The moment I set up that instance I'll push credentials to the team.
