### ISSUE TITLE
Try tweet-scraping with pure HTTP requests?

### ISSUE THREAD

**Issue by NWChen** [NWChen/banshee#5]
The interface you expose through `twitter_requests.py` looks good to me.

@OriAboodi what do you think about just scraping via HTTP GET requests, e.g. with `BeautifulSoup`/similar? Bringing this up since I anticipate users might object to creating a Twitter account/adding an API token.

**Comment by OriAboodi** [comment]
@NWChen Definitely possible! This won't be too difficult either. I guess we should save this for a later iteration of the product?
We will also want to really be specific on the HTTP requests we're doing here, as it will take more customization than the tweepy interface

**Comment by pr** [comment]
@NWChen @OriAboodi From what SSG Jefferson said, First IO will hate having to make a Twitter account for this. Let's try to avoide that at all costs.

**Comment by NWChen** [comment]
@OriAboodi could you implement HTTP/GET-only web scraping? libraries `requests` by Kenneth Reitz and `BeautifulSoup` should simplify your life here - you may already know about them.

**Comment by OriAboodi** [comment]
@NWChen i had a few other projects I had to prioritize this weekend. Gotta push back on the HTTP requests till later in the week I think.
