### ISSUE TITLE
Real Time Results Streaming 

### ISSUE THREAD

**Issue by pr** [NWChen/banshee#6]
@NWChen Do you think once you implement real time results streaming the way I format the results will change? I'm wary to sink time into formating the current results because I think the changes you will need to make the socket.io code will change how the results are delivered.

**Comment by NWChen** [comment]
Thanks @pr  for tagging w/ `question`ge

I think maintaining the results as a large 50% screen-width `div` is fine. 

FYI the backend will send the client JSON via websockets with format something like
```json
"tweet_uid": {
    "content": [
             {
               "text_type":"normal",
               "text":"this example tweet includes some"
             },
             {
               "text_type":"important",
               "text":"provocative"
             },
             {
               "text_type":"normal",
               "text":"words that will be highlighted"
             }
        ]
    "author": "tweeter_username",
    ...
}
```

such that the backend will search thru raw tweet data for important tokens, and JS on the clientside can extract those tokens from the received JSON and render those tokens.

**Comment by pr** [comment]
@NWChen That looks great to me! 

Also side note, maybe we begin to think about what link we want to send out to people?
h4d.herokuapp.com is avaliable, banshee.herokuapp.com is not. 
Also super easy to deploy to custom url, I got it on h4d.peter.net in 5 minutes. 

In light of that, maybe we even register something like banshee.tld to send to First IO? Bunch of random ones on namecheap for a couple bucks.
