### ISSUE TITLE
Handling Chrome driver

### ISSUE THREAD

**Issue by OriAboodi** [NWChen/banshee#7]
Hey @NWChen 
I used a package called 'selenium' to dynamically load content on a chrome webpage.
One big thing is that for this to work, in the system PATH we will need to have the chrome driver .exe file. I did this locally on my machine, but I think we may either need to include it in the package on banshee or include it in the instructions for downloading the project.
There's a way to modify inside the code itself where the PATH can look for the driver, but this may be something we need to work on to get the new functionality up and running.

We may need to talk about this/work together, so let me know!

**Comment by NWChen** [comment]
@OriAboodi good question.

I'm surprised `selenium` required the chrome exe in PATH. My concern is that 1st IO users might not be using chrome - to my knowledge Internet Explorer is actually the default (and perhaps only) browser in use across US Army.

Is there no workaround for this in `requests` or similar packages?

**Comment by OriAboodi** [comment]
@NWChen 
I don't think it actually really matter what they use, since the driver is only the browser that we get the information from. I don't think it's going to change how they see this, but we could perhaps implement it using explorer if it becomes an issue.
I couldn't easily find a better way to dynamically load content, since most sites are using AJAX these days. When we deploy the server, will this be an issue? can we include the driver in our package?

**Comment by NWChen** [comment]
@OriAboodi unfortunately I don't see a way for us to deploy `chrome.exe` with the live version of the webapp, since Heroku has no provision for Windows servers/cannot run `.exe` executables.

Is it possible to use a WebKit platform like PhantomJS to dynamically load content?
