### ISSUE TITLE
Scrolling implications of scraper

### ISSUE THREAD

**Issue by OriAboodi** [NWChen/banshee#8]
Hey @NWChen
**Scrolling:**
The way I implemented keyword search is that it captures all tweets on a search-query webpage by number of seconds it was scrolled. Depending on how much content is on each webpage, the number of actual tweets can vary per keyword-search function invocation.

What's your opinion on this? I feel like we will need to keep a close eye on its implications.

**Comment by NWChen** [comment]
@OriAboodi could you clarify what you mean by  'scrolling' here, specifically:

> by number of seconds it was scrolled

do you mean literally how long the tweet lasts on the current webpage view?

**Comment by OriAboodi** [comment]
@NWChen 
Basically, the function I implemented takes in a int variable. That variable decided how many times a page is "scrolled down", which loads more content/tweets onto the page. The problem is that Tweets only get loaded onto the front end when the user scrolls down, so the more times we scroll the more tweets there will be.
This is also why we needed a package like Selenium to load to page using a driver/browser

What I meant by implications is that lets say we hit the function once, with only 1 scroll, getting all the latest tweets. Then, your automation to get the "live feed" pings the function again a minute later to get the new tweets. However, perhaps there were no new tweets in that time frame. The function will still return all those original tweets that were returned the first time we hit the function. Do you see the issue? we might have duplicates that way. Could be useful to store the tweets that are returned in a hashmap of some sort using the tweet id as the unique identifier.

**Comment by NWChen** [comment]
@OriAboodi OK - thanks for clarifying.

I realize realtime streaming depends on the same functionality you're talking about (filtering duplicates and yielding new data). I can look into setting up a DB to track tweets.
